import environ

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

DJANGO_SECRET_KEY=str(env('DJANGO_SECRET_KEY'))
DEBUG=bool(env('DEBUG'))
DATABASE_NAME=str(env('DATABASE_NAME'))
DATABASE_USERNAME=str(env('DATABASE_USERNAME'))
DATABASE_PASSWORD=str(env('DATABASE_PASSWORD'))
DATABASE_HOST=str(env('DATABASE_HOST'))
DATABASE_PORT=str(env('DATABASE_PORT'))
OTP_DIGITS=int(env('OTP_DIGITS'))
ENCRYPTION_SALT=str(env('ENCRYPTION_SALT'))
LOGIN_TTL_SECONDS=int(env('LOGIN_TTL_SECONDS'))
ENCRYPTION_TTL_SECONDS=int(env('ENCRYPTION_TTL_SECONDS'))
JWT_TTL_SECONDS=int(env('JWT_TTL_SECONDS'))
REDIS_HOST=str(env('REDIS_HOST'))
REDIS_PORT=str(env('REDIS_PORT'))
REDIS_DB=int(env('REDIS_DB'))
REDIS_PASSWORD=str(env('REDIS_PASSWORD'))


