messages={
    'dob_invalid' : 'Invalid Date of birth',
    'dob_underage' : 'User need to be atleast 18 years old',
    'data_error':"Data saving error",
    'email_invalid' : 'Invalid Email',
    'email_exist' : 'Email already exists',
    'email_not_avilable' : 'Email already registerd by other user',
    'loggedin':'logged in Successfully',
    'loggedin_failed':'logged in failed',
    'logout':'logged out Successfully',
    'logout_failed':'logged out failed',
    'maximum_request' : 'Too many request in a short time,Try later',
    'name_invalid' : 'Invalid name',
    'otp_created' :'OTP sent to registerd phone',
    'otp_failed' :'OTP failed',
    'otp_invalid': 'OTP is invalid',
    'ph_invalid' : 'Invalid Phone number',
    'ph_exist' : 'Phone number already exists',
    'ph_not_found' : 'Phone number not found',
    'superuser_created' : 'Super user created',
    'superuser_not_created' : 'Super user creation failed',
    'user_created':'User created',
    'user_not_found':'User not found',
    'user_not_created':'User creation failed',
    'user_session_expired':'User session expired',
    'wrong_credentials':"Credentials are either missing or Wrong",

}
status_code = {
    '200':'Ok',
    '201':'Created',
    '204':'No Content',
    '401':'Unauthorized',
    '403':'Forbidden',
    '404':'Not Found',
    '409':'Conflict',
    '422':'Unprocessable Entity',
    '429':'Too Many Requests',
    '500':'Internal Server Error',

}